version: '3'

services:
    nginx:
        image: 'nginx:stable'
        restart: always
        working_dir: /app
        volumes:
            - ./:/app
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8000:80"
        depends_on:
            - php
        networks:
            - reverb-example-network

    php:
        build: docker/php
        image: my_php
        restart: always
        working_dir: /app
        ports:
            - "9000:9000"
        volumes:
            - ./:/app/
        networks:
            - reverb-example-network

    reverb:
        build: docker/php
        image: my_php
        restart: always
        working_dir: /app
        command: php artisan reverb:start --debug
        volumes:
            - ./:/app/
        ports:
            - "8080:8080" #reverb port
        networks:
            - reverb-example-network
volumes:
    dbdata:
        driver: local

networks:
    reverb-example-network:
        driver: bridge
